language: generic
sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_2a342fc881c5_key -iv $encrypted_2a342fc881c5_iv -in deploy_key.enc -out deploy_key -d

script: bash ./deploy.sh

env:
  global:
    - COMMIT_AUTHOR_NAME="Travis CI"
    - COMMIT_AUTHOR_EMAIL="travis-ci@w3.org"
    - SPECS="index"
